#version: '3.8'
#services:
#  spring-boot-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#  mysql:
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: 12345
#      MYSQL_DATABASE: emp_service
#    ports:
#      - "3306:3306"
#
##version: '3.1'
##
##services:
##
##  db:
##    image: mysql
##    restart: always
##    ports:
##      - "3307:3306"
##    environment:
##      MYSQL_ROOT_PASSWORD: 12345
##      MYSQL_DATABASE: emp_service
#
#
#
